name: Go

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        cache: false

    - name: Build
      run: go build -v ./...

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        cache: false

    - name: Test
      run: go test -v ./...

  tests-race:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        cache: false

    - name: Test
      run: go test -race -v ./...

  lint:
    needs: [tests, tests-race]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          cache: false

      - uses: golangci/golangci-lint-action@v8
        with:
          skip-cache: true